[package]
name = "wasm-peers"
version = "0.3.0"
authors = ["Tomasz Karwowski <to.karwowski@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Easy-to-use wrapper for WebRTC DataChannels peer-to-peer connections written in Rust and compiling to WASM."
#homepage
repository = "https://github.com/wasm-peers/wasm-peers"
keywords = ["wasm", "webrtc", "datachannels", "peer-to-peer", "udp", "tcp", "browser", "webassembly"]
categories = ["wasm", "network-programming", "web-programming"]
readme = "../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["one-to-one", "one-to-many", "many-to-many", "console_error_panic_hook"]
one-to-one = []
one-to-many = []
many-to-many = []

[dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-json-wasm = "0.3"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
log = "0.4"
wasm-logger = "0.2"
uuid = { version = "0.8", features = ["v4", "stdweb"] }

wasm-peers-protocol = { path = "../protocol", version = "0.3" }

[dependencies.web-sys]
version = "0.3.22"
features = [
    "console",

    # WebRTC features
    "MessageEvent",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceConnectionState",
    "RtcIceCandidate",
    "RtcIceCandidateInit",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcConfiguration",
    "RtcIceGatheringState",

    # Tests
    "RtcSessionDescription",

    # WebSocket features
    "WebSocket",
    "BinaryType",
]

[dev-dependencies]
mockall = "*"
wasm-bindgen-test = "0.3"
